import { Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { Screen } from "@/components/Screen";
import { Brand } from "@/components/Brand";
import { colors, spacing } from "@/theme";
import { i18n } from "@/i18n";
import { useAppStore } from "@/store";
export default function Settings() { const { language, setLanguage, cameraEnabled, setCamera, signOut } = useAppStore(); i18n.locale = language; return <Screen><View style={styles.top}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Brand /></View><Text style={styles.title}>{i18n.t("settings")}</Text><View style={styles.card}><Text style={styles.label}>{i18n.t("language")}</Text><Pressable onPress={() => setLanguage(language === "en" ? "si" : "en")} style={styles.row}><Text style={styles.value}>{language === "en" ? "English" : "සිංහල"}</Text><Text style={styles.change}>Change</Text></Pressable><Text style={styles.label}>Camera sensing</Text><Pressable onPress={() => setCamera(!cameraEnabled)} style={styles.row}><Text style={styles.value}>{cameraEnabled ? i18n.t("cameraOn") : i18n.t("cameraOff")}</Text><Text style={styles.change}>{cameraEnabled ? i18n.t("disableCamera") : i18n.t("enableCamera")}</Text></Pressable></View><Pressable onPress={() => { signOut(); router.replace("/(auth)/sign-in"); }} style={styles.signOut}><Text style={styles.signOutText}>{i18n.t("signOut")}</Text></Pressable></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: "row", alignItems: "center", gap: 18 }, back: { color: colors.sageDark, fontSize: 34 }, title: { color: colors.ink, fontSize: 28, fontWeight: "800", marginTop: 40, marginBottom: 20 }, card: { backgroundColor: colors.card, borderRadius: 20, padding: spacing.md, gap: 14 }, label: { color: colors.muted, fontSize: 12, fontWeight: "800", textTransform: "uppercase", letterSpacing: 1 }, row: { minHeight: 48, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.border }, value: { color: colors.ink, fontSize: 15 }, change: { color: colors.sageDark, fontWeight: "700", fontSize: 13 }, signOut: { marginTop: 24, alignItems: "center", padding: 14 }, signOutText: { color: colors.safety, fontWeight: "800" } });
