import { I18n } from "i18n-js";

export const translations = {
  en: {
    appName: "MaternaLink", tagline: "A gentle space to pause and be heard.", welcome: "Welcome back", signInHint: "Sign in to keep your conversations together.", email: "Email", password: "Password", signIn: "Continue", demoAccount: "Try the demo", noAccount: "New here?", createAccount: "Create an account", chatTitle: "Your safe space", chatSubtitle: "Share what is on your mind. You can take your time.", emptyTitle: "You can start wherever feels easiest", emptyBody: "There is no right way to begin. I am here to listen.", placeholder: "Write a message…", send: "Send", online: "Demo mode · ready", cameraOff: "Camera is off", cameraOn: "Camera sensing is on", enableCamera: "Enable camera", disableCamera: "Turn camera off", consentTitle: "Your privacy comes first", consentBody: "Camera sensing is optional. If enabled, a temporary face crop is sent to the MaternaLink service for processing and is never saved. You can turn it off at any time.", consentAccept: "I understand and enable", keepOff: "Keep camera off", safetyTitle: "You do not have to face this alone", safetyBody: "I am glad you told me. Please reach out to someone you trust or your local emergency service if you may be in immediate danger.", retry: "Try again", error: "We could not send that just now.", supportive: "A little extra care", mood: { calm: "Calm", neutral: "Neutral", distressed: "Here with you", unknown: "Listening" }, settings: "Settings", language: "Language", signOut: "Sign out", devPanel: "Demo controls", responseMode: "Response style", moodState: "Mood state", simulateFailure: "Next message fails", suggestion: "Try a gentle breathing pause", suggestionBody: "Inhale slowly for four counts, then exhale for six."
  },
  si: {
    appName: "MaternaLink", tagline: "නැවතී, සවන් දීමට ඇති මෘදු අවකාශයක්.", welcome: "නැවත සාදරයෙන් පිළිගනිමු", signInHint: "ඔබේ සංවාද එකට තබා ගැනීමට ඇතුළු වන්න.", email: "විද්‍යුත් තැපෑල", password: "මුරපදය", signIn: "ඉදිරියට යන්න", demoAccount: "Demo උත්සාහ කරන්න", noAccount: "අලුත් ද?", createAccount: "ගිණුමක් සාදන්න", chatTitle: "ඔබේ ආරක්ෂිත අවකාශය", chatSubtitle: "ඔබේ සිතේ ඇති දේ බෙදාගන්න. ඔබට අවශ්‍ය කාලය ගන්න.", emptyTitle: "පහසු යැයි හැඟෙන තැනින් පටන් ගන්න", emptyBody: "ආරම්භ කිරීමට නිවැරදි ක්‍රමයක් නැත. මම සවන් දීමට මෙහි සිටිමි.", placeholder: "පණිවිඩයක් ලියන්න…", send: "යවන්න", online: "Demo මාදිලිය · සූදානම්", cameraOff: "කැමරාව වසා ඇත", cameraOn: "කැමරා සංවේදනය ක්‍රියාත්මකයි", enableCamera: "කැමරාව ක්‍රියාත්මක කරන්න", disableCamera: "කැමරාව වසන්න", consentTitle: "ඔබේ පෞද්ගලිකත්වය ප්‍රමුඛයි", consentBody: "කැමරා සංවේදනය විකල්පයකි. ක්‍රියාත්මක කළහොත්, තාවකාලික මුහුණු crop එකක් MaternaLink සේවාවට යවනු ලබන අතර කිසිවිටෙක සුරැකෙන්නේ නැත. ඔබට ඕනෑම විටෙක එය වසා දැමිය හැක.", consentAccept: "මට වැටහේ, කැමරාව ක්‍රියාත්මක කරන්න", keepOff: "කැමරාව වසා තබන්න", safetyTitle: "ඔබට මෙය තනිව මුහුණ දීමට අවශ්‍ය නැත", safetyBody: "ඔබ මට පැවසීම ගැන සතුටුයි. ඔබට විශ්වාසවන්ත කෙනෙකුට හෝ හදිසි අවස්ථාවක ඔබේ ප්‍රදේශයේ හදිසි සේවාවකට සම්බන්ධ වන්න.", retry: "නැවත උත්සාහ කරන්න", error: "දැන් එය යැවීමට නොහැකි විය.", supportive: "අමතර සැලකිල්ලක්", mood: { calm: "සන්සුන්", neutral: "මධ්‍යස්ථ", distressed: "ඔබ සමඟයි", unknown: "සවන් දෙමින්", }, settings: "සැකසුම්", language: "භාෂාව", signOut: "ඉවත් වන්න", devPanel: "Demo පාලන", responseMode: "ප්‍රතිචාර රටාව", moodState: "මනෝභාව තත්ත්වය", simulateFailure: "ඊළඟ පණිවිඩය අසාර්ථක කරන්න", suggestion: "මෘදු හුස්ම ගැනීමේ විරාමයක් උත්සාහ කරන්න", suggestionBody: "හතරට සෙමින් හුස්ම ගෙන හයට පිට කරන්න."
  }
};
translations.en.emptyBody = "There is no right way to begin. I am here to listen.";
translations.en.placeholder = "I'm here to help.";
export const i18n = new I18n(translations);
i18n.enableFallback = true;
