import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { Brand } from "@/components/Brand";
import { Screen } from "@/components/Screen";
import { colors, spacing } from "@/theme";
import { useAppStore } from "@/store";
import { i18n } from "@/i18n";
export default function SignIn() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const signInAnonymously = useAppStore(s => s.signInAnonymously); const language = useAppStore(s => s.language); const setLanguage = useAppStore(s => s.setLanguage); i18n.locale = language; return <Screen><View style={styles.top}><Brand /><Pressable accessibilityRole="button" onPress={() => setLanguage(language === "en" ? "si" : "en")}><Text style={styles.lang}>{language === "en" ? "සිංහල" : "English"}</Text></Pressable></View><View style={styles.hero}><Text style={styles.eyebrow}>MAATHRU CARE</Text><Text style={styles.title}>{i18n.t("welcome")}</Text><Text style={styles.subtitle}>{i18n.t("tagline")}</Text></View><View style={styles.card}><Text style={styles.hint}>{i18n.t("signInHint")}</Text><TextInput accessibilityLabel={i18n.t("email")} placeholder={i18n.t("email")} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" style={styles.input} /><TextInput accessibilityLabel={i18n.t("password")} placeholder={i18n.t("password")} value={password} onChangeText={setPassword} secureTextEntry style={styles.input} /><Pressable style={styles.button} onPress={() => { void signInAnonymously().then(() => { if (useAppStore.getState().authenticated) router.replace("/(app)/chat"); }); }}><Text style={styles.buttonText}>{i18n.t("signIn")}</Text></Pressable><Pressable style={styles.demo} onPress={() => { void signInAnonymously().then(() => { if (useAppStore.getState().authenticated) router.replace("/(app)/chat"); }); }}><Text style={styles.demoText}>{i18n.t("demoAccount")}</Text></Pressable></View><Text style={styles.footer}>{i18n.t("noAccount")}  <Text style={styles.link}>{i18n.t("createAccount")}</Text></Text></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, lang: { color: colors.sageDark, fontWeight: "700", padding: 12 }, hero: { marginTop: 70, marginBottom: 30 }, eyebrow: { color: colors.sageDark, letterSpacing: 2, fontSize: 12, fontWeight: "800" }, title: { color: colors.ink, fontSize: 34, fontWeight: "800", marginTop: 10 }, subtitle: { color: colors.muted, fontSize: 17, lineHeight: 26, maxWidth: 400, marginTop: 10 }, card: { backgroundColor: colors.card, borderRadius: 24, padding: spacing.lg, gap: 14, ...{ boxShadow: "0 15px 35px rgba(41,65,52,.08)" } as any }, hint: { color: colors.muted, fontSize: 15, lineHeight: 22, marginBottom: 3 }, input: { backgroundColor: colors.paper, borderRadius: 13, padding: 15, minHeight: 52, fontSize: 16, color: colors.ink }, button: { backgroundColor: colors.sageDark, minHeight: 52, borderRadius: 13, alignItems: "center", justifyContent: "center", marginTop: 4 }, buttonText: { color: colors.white, fontWeight: "800", fontSize: 16 }, demo: { alignItems: "center", padding: 10 }, demoText: { color: colors.sageDark, fontWeight: "700" }, footer: { color: colors.muted, textAlign: "center", marginTop: 26 }, link: { color: colors.sageDark, fontWeight: "700" } });
